"""empty message

Revision ID: 463de4c0031f
Revises: ea17f340c750
Create Date: 2022-08-25 05:06:06.243545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463de4c0031f'
down_revision = 'ea17f340c750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
