"""empty message

Revision ID: ea17f340c750
Revises: 573ee4414033
Create Date: 2022-08-25 04:09:11.426423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea17f340c750'
down_revision = '573ee4414033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access')
    # ### end Alembic commands ###
